# Site settings
title: Ouranos Systems
email: robert@ouranos.systems
url: https://ouranossystems.github.io
description: "Powering Space"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ouranos Systems Pty Ltd

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: linkedin
    url: https://www.linkedin.com/company/ouranos-systems-pty-ltd
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: instagram
    url: https://www.instagram.com/ouranos.systems/?hl=en


# Build settings
markdown: kramdown
permalink: pretty
